from enum import Enum


class MissionStatus(str, Enum):
    CREATED = "CREATED"
    PLANNING = "PLANNING"
    PLANNED = "PLANNED"
    APPROVED_FOR_EXECUTION = "APPROVED_FOR_EXECUTION"
    EXECUTING = "EXECUTING"
    VERIFYING = "VERIFYING"
    RECOVERING = "RECOVERING"
    VERIFIED = "VERIFIED"
    PR_READY = "PR_READY"
    AWAITING_HUMAN_APPROVAL = "AWAITING_HUMAN_APPROVAL"
    MERGED = "MERGED"
    CANCELLED = "CANCELLED"
    ABORTED = "ABORTED"
    BLOCKED = "BLOCKED"
    FAILED_PERMANENTLY = "FAILED_PERMANENTLY"
