from enum import Enum


class AgentType(str, Enum):
    CODING_AGENT = "CODING_AGENT"
    PLANNER_AGENT = "PLANNER_AGENT"


class AgentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DEPRECATED = "DEPRECATED"


class AgentCapability(str, Enum):
    READ_REPOSITORY = "READ_REPOSITORY"
    WRITE_REPOSITORY = "WRITE_REPOSITORY"
    SEARCH_REPOSITORY = "SEARCH_REPOSITORY"
    RUN_TESTS = "RUN_TESTS"
    RUN_COMMAND = "RUN_COMMAND"
    READ_GIT = "READ_GIT"
    WRITE_GIT = "WRITE_GIT"
    FINISH_TASK = "FINISH_TASK"


class AgentRunStatus(str, Enum):
    CREATED = "CREATED"
    READY = "READY"
    RUNNING = "RUNNING"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"
    POLICY_REJECTED = "POLICY_REJECTED"


class ToolCallStatus(str, Enum):
    PENDING = "PENDING"
    ALLOWED = "ALLOWED"
    REJECTED = "REJECTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"


class ActionType(str, Enum):
    READ_FILE = "READ_FILE"
    LIST_DIRECTORY = "LIST_DIRECTORY"
    SEARCH_REPOSITORY = "SEARCH_REPOSITORY"
    WRITE_FILE = "WRITE_FILE"
    RUN_COMMAND = "RUN_COMMAND"
    GET_GIT_STATUS = "GET_GIT_STATUS"
    GET_GIT_DIFF = "GET_GIT_DIFF"
    RUN_TESTS = "RUN_TESTS"
    FINISH_TASK = "FINISH_TASK"
