from enum import Enum


class AgentType(str, Enum):
    CODING_AGENT = "CODING_AGENT"
    PLANNER_AGENT = "PLANNER_AGENT"
    DEBUGGER_AGENT = "DEBUGGER_AGENT"
    TESTER_AGENT = "TESTER_AGENT"
    SECURITY_REVIEWER_AGENT = "SECURITY_REVIEWER_AGENT"
    CODE_REVIEWER_AGENT = "CODE_REVIEWER_AGENT"
    DOCUMENTATION_AGENT = "DOCUMENTATION_AGENT"
    RELEASE_AGENT = "RELEASE_AGENT"


class AgentStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    DEPRECATED = "DEPRECATED"


class AgentCapability(str, Enum):
    READ_REPOSITORY = "READ_REPOSITORY"
    WRITE_REPOSITORY = "WRITE_REPOSITORY"
    SEARCH_REPOSITORY = "SEARCH_REPOSITORY"
    RUN_TESTS = "RUN_TESTS"
    RUN_COMMAND = "RUN_COMMAND"
    READ_GIT = "READ_GIT"
    WRITE_GIT = "WRITE_GIT"
    FINISH_TASK = "FINISH_TASK"
    DEBUG_CODE = "DEBUG_CODE"
    ANALYZE_TESTS = "ANALYZE_TESTS"
    SECURITY_ANALYSIS = "SECURITY_ANALYSIS"
    CODE_REVIEW = "CODE_REVIEW"
    GENERATE_DOCS = "GENERATE_DOCS"
    RELEASE_MANAGEMENT = "RELEASE_MANAGEMENT"


class AgentRunStatus(str, Enum):
    CREATED = "CREATED"
    READY = "READY"
    RUNNING = "RUNNING"
    VERIFYING = "VERIFYING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"
    POLICY_REJECTED = "POLICY_REJECTED"


class ToolCallStatus(str, Enum):
    PENDING = "PENDING"
    ALLOWED = "ALLOWED"
    REJECTED = "REJECTED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    TIMED_OUT = "TIMED_OUT"


class AgentTaskStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    ASSIGNED = "ASSIGNED"
    RUNNING = "RUNNING"
    WAITING = "WAITING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    RETRYING = "RETRYING"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class WorkflowStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AssignmentStatus(str, Enum):
    ASSIGNED = "ASSIGNED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ActionType(str, Enum):
    READ_FILE = "READ_FILE"
    LIST_DIRECTORY = "LIST_DIRECTORY"
    SEARCH_REPOSITORY = "SEARCH_REPOSITORY"
    WRITE_FILE = "WRITE_FILE"
    RUN_COMMAND = "RUN_COMMAND"
    GET_GIT_STATUS = "GET_GIT_STATUS"
    GET_GIT_DIFF = "GET_GIT_DIFF"
    RUN_TESTS = "RUN_TESTS"
    FINISH_TASK = "FINISH_TASK"


class MessageType(str, Enum):
    CONTEXT_REQUEST = "CONTEXT_REQUEST"
    CONTEXT_RESPONSE = "CONTEXT_RESPONSE"
    PROGRESS = "PROGRESS"
    RESULT = "RESULT"
    FAILURE = "FAILURE"
    REVIEW_FINDING = "REVIEW_FINDING"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    RECOVERY_REQUEST = "RECOVERY_REQUEST"
